spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka

management:
  security:
    enabled: false

#zuul:
#  routes:
#    hello-service:
#      path: /somepath1/**
#      service-id: hello
#    goodbye-service:
#      path: /somepath2/**
#      service-id: goodbye

#zuul:
#  routes:
#    hello-service:
#      path: /somepath1/**
#      service-id: hello
#    goodbye-service:
#      path: /goodbye/**
#      service-id: goodbye